### ISSUE TITLE
Using for other Advices like @After,Before,AfterThrowing

### ISSUE THREAD

**Issue by upen4a3** [Ananto30/loggable#2]
Hey @Ananto30  Thanks for the great explanation and project.I am able to use with Around aspect successfully. It would be great if you can provide some example around other Advices as well thanks.

I tried to use below
```

  @Before(value = "execution(* com.abc.xyz..restclients...*(..))")
    fun logBeforeAllMethods(joinPoint: JoinPoint) {

        log.info("Request : " + joinPoint.signature.declaringTypeName + Arrays.toString(joinPoint.args))


    }

    @AfterReturning(value = "execution(* com.abc.xyz..restclients..*(..))")
    fun logAfterAllMethods(joinPoint: JoinPoint) {
        log.info("Response : " + joinPoint.signature.declaringTypeName + Arrays.toString(joinPoint.args))
    }
```

But both are printing same values expectation is print method input and output.

**Comment by Ananto30** [comment]
Can you please explain what problems are you facing?
Hope you have made a bean of this class. And I need to do some fixes in this example too, but can't manage time. Will do other examples in my free time hopefully.

**Comment by Ananto30** [comment]
Closing this as no reply from @upen4a3
