### ISSUE TITLE
question about how this work

### ISSUE THREAD

**Issue by maschietto** [Ananto30/loggable#3]
I put the logger annotation and logger aspect in my project and also annotated method in my controller but nothing happens, i tried also with code on git-hub repo but nothing changed. 
When I try to debug debugger don't get to this point? 
do u have any idea?

**Comment by Ananto30** [comment]
You have to make a bean of logger aspect. Like this - 
```java
@Bean
public LoggerAspect loggerAspect() {
    return new LoggerAspect();
}
```
Have you done it?

**Comment by maschietto** [comment]
> You have to make a bean of logger aspect. Like this -
> 
> ```java
> @Bean
> public LoggerAspect loggerAspect() {
>     return new LoggerAspect();
> }
> ```
> 
> Have you done it?

I just put @Component and everything works fine. Thanks. :)

**Comment by Ananto30** [comment]
Closing this as the issue was solved.
